# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18 as the base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependencies installation
COPY package.json ./
COPY bun.lock ./
COPY tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src ./src

# Build the project
RUN npx tsup src/index.ts --format esm --dts

# Use a lightweight node image to reduce the image size
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy built files and node modules from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Expose port (default to 3000 but can be changed)
EXPOSE 3000

# Environment variables
ENV PORT=3000

# Run the server
CMD ["node", "dist/index.js"]
